import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider, Spin } from "antd";
import "antd/dist/reset.css";
import { GlobalContextProvider } from "@/context/GlobalContextProvider";
import reducer, { initState } from "@/context/reducer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#143642",
              // fontFamily: "Montserrat",
            },
            components: {
              Segmented: {
                colorBgElevated: "#E4E835",
              },
            },
          }}
        >
          <GlobalContextProvider reducer={reducer} initialState={initState}>
            {children}
          </GlobalContextProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
